### ISSUE TITLE
How to set beneficiaries?

### ISSUE THREAD

**Issue by ektorcaba** [hernandev/sc2-sdk-php#9]
Hi,help please!, how to set beneficiaries for comment options?

**Comment by ektorcaba** [comment]
no options for beneficiaries? :(

**Comment by ektorcaba** [comment]
I write it on /Operations/CommentOptions.php

`public function beneficiaries(array $beneficiaries = []) : self
    {
        return $this->setParameter('extensions.beneficiaries', $beneficiaries);
    }`
now on my script:

`$options->beneficiaries([['acount'=>'good-karma','weight'=>1000]]);`

The request is fine but error in response:

`SteemConnect\Exceptions\ResponseException: server_error: transaction.operations = comment,[object Object],comment_options,[object Object]	cause: comment_options.extensions = [object Object]	cause: Illegal value: undefined (not an integer) stack: TypeError: Illegal value: undefined (not an integer) at ByteBuffer.module.exports.ByteBufferPrototype.writeVarint32 (/app/node_modules/bytebuffer/dist/bytebuffer-node.js:1481:23) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:502:15) at Serializer.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:71:26) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:846:26) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:397:30) at Serializer.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:71:26) at Serializer.toByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:198:18) at Serializer.toBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:204:36) at Object.Auth.signTransaction (/app/node_modules/@steemit/steem-js/lib/auth/index.js:116:24) at /app/node_modules/@steemit/steem-js/lib/broadcast/index.js:52:64 at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18) at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57) at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:524:17) at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18) stack: Error: comment_options.extensions = [object Object]	cause: Illegal value: undefined (not an integer) stack: TypeError: Illegal value: undefined (not an integer) at ByteBuffer.module.exports.ByteBufferPrototype.writeVarint32 (/app/node_modules/bytebuffer/dist/bytebuffer-node.js:1481:23) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:502:15) at Serializer.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:71:26) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:846:26) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:397:30) at Serializer.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:71:26) at Serializer.toByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:198:18) at Serializer.toBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:204:36) at Object.Auth.signTransaction (/app/node_modules/@steemit/steem-js/lib/auth/index.js:116:24) at /app/node_modules/@steemit/steem-js/lib/broadcast/index.js:52:64 at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18) at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57) at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:524:17) at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18) at Function._throw (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/error_with_cause.js:35:19) at Serializer.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:78:29) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:846:26) at Object.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/types.js:397:30) at Serializer.appendByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:71:26) at Serializer.toByteBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:198:18) at Serializer.toBuffer (/app/node_modules/@steemit/steem-js/lib/auth/serializer/src/serializer.js:204:36) at Object.Auth.signTransaction (/app/node_modules/@steemit/steem-js/lib/auth/index.js:116:24) at /app/node_modules/@steemit/steem-js/lib/broadcast/index.js:52:64 at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18) at Promise._resolveCallback (/app/node_modules/bluebird/js/release/promise.js:432:57) at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:524:17) at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18) at Promise._fulfill (/app/node_modules/bluebird/js/release/promise.js:638:18) at /app/node_modules/bluebird/js/release/nodeback.js:42:21 in /var/www/html/steemule/lib/sc2-sdk-php-master/src/Client/Broadcaster.php:158 Stack trace: #0 /var/www/html/steemule/lib/sc2-sdk-php-master/src/Client/Client.php(276): SteemConnect\Client\Broadcaster->broadcast(Array) #1 /var/www/html/steemule/___autopost.php(127): SteemConnect\Client\Client->broadcast(Object(SteemConnect\Operations\Comment), Object(SteemConnect\Operations\CommentOptions)) #2 {main}`

Any idea?

thank you!

**Comment by ektorcaba** [comment]
Ok, i try with curl with the same results, it appear to be a bug on steemconnect server
https://github.com/steemit/steem-js/issues/124

**Comment by ektorcaba** [comment]
ok, with this now is ok:

`$options->beneficiaries(json_decode('[[0,{"beneficiaries": [{"account": "user", "weight": 1000}]}]]'));`

Thank you

**Comment by HagosAlema** [comment]
@ektorcaba Would you mind helping me out on this? Because, I am getting the same error like what you wrote above even if I use 
`$options->beneficiaries(json_decode('[[0,{"beneficiaries": [{"account": "user", "weight": 1000}]}]]'));`

Thanks in advance.
